version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/products
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:5173
      - PORT=3000
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:16
    container_name: postgres-products
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-products
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
