[build]
builder = "DOCKERFILE"
dockerfilePath = "docker-compose.yml"

[deploy]
startCommand = "docker-compose up"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
NODE_ENV = "production" 